server:
  port: 8082

logging:
  level:
    org:
      apache:
        http: debug

      springframework:
        web:
          client:
            RestTemplate: debug
    httpclient:
      wire: debug

trust:
  store:
    classpath: classpath:keystore/key.p12
    password: password